### ISSUE TITLE
Fix bug zero-valued RMS values

### ISSUE THREAD

**Issue by dncnwtts** [Cosmoglobe/Commander#145] opened 2022-09-21 09:58 UTC
With a new effective chi-squared calculation that I added, I introduced a divide by zero error when there are rms maps with values of zero.

https://github.com/Cosmoglobe/Commander/blob/01243d94d7f856556d4058e81e6a4f77e4ef6da0/commander3/src/comm_output_mod.f90#L373

Needs to be fixed so that the chi-squared is only calculated for the unmasked pixels

**Comment by unfunfunt** [comment] 2022-11-08 13:36
Duplicate of issue #146

**Closed by unfunfunt** 2022-11-08 13:36 UTC
